<?php

use App\Http\Controllers\Admin\InstructorAssignmentController;
use App\Http\Controllers\Admin\InstructorController;
use App\Http\Controllers\Admin\StudentController as AdminStudentController;
use App\Http\Controllers\Admin\SubjectController;
use App\Http\Controllers\Admin\UserAccountController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ExcuseRequestController;
use App\Http\Controllers\ExcuseRequestSettingController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RealtimeController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\RegistrationController;
use App\Http\Controllers\StudentEmailVerificationController;
use App\Http\Controllers\VerificationController;
use App\Http\Controllers\WorkflowController;
use Illuminate\Support\Facades\Route;

Route::get('/', fn () => auth()->check() ? redirect()->route('dashboard') : view('auth.login'));
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login', [AuthController::class, 'authenticate'])->name('login.attempt');
    Route::get('/register', [RegistrationController::class, 'create'])->name('register');
    Route::post('/register', [RegistrationController::class, 'store'])->name('register.store');
    Route::post('/register/send-otp', [RegistrationController::class, 'sendOtp'])->middleware('throttle:2,1')->name('register.send-otp');
    Route::get('/register/verify-email', [StudentEmailVerificationController::class, 'show'])->name('register.verify-email');
    Route::post('/register/verify-email', [StudentEmailVerificationController::class, 'verify'])->middleware('throttle:10,1')->name('register.verify-email.store');
    Route::post('/register/verify-email/resend', [StudentEmailVerificationController::class, 'resend'])->middleware('throttle:2,1')->name('register.verify-email.resend');
    Route::get('/forgot-password', [AuthController::class, 'forgot'])->name('password.request');
    Route::post('/forgot-password', [AuthController::class, 'emailReset'])->name('password.email');
    Route::get('/reset-password/{token}', [AuthController::class, 'reset'])->name('password.reset');
    Route::post('/reset-password', [AuthController::class, 'updatePassword'])->name('password.update');
});
Route::get('/verify/{reference}', [VerificationController::class, 'show'])->name('verify');
Route::middleware('auth')->group(function () {
    Route::get('/realtime/version', [RealtimeController::class, 'version'])->middleware('throttle:30,1')->name('realtime.version');
    Route::get('/realtime/presence', [RealtimeController::class, 'presence'])->middleware('throttle:30,1')->name('realtime.presence');
    Route::get('/messages', [MessageController::class, 'index'])->name('messages.index');
    Route::get('/messages/archived', [MessageController::class, 'index'])->name('messages.archived');
    Route::post('/messages/select/{student}', [MessageController::class, 'select'])->name('messages.select');
    Route::post('/messages/{student}', [MessageController::class, 'store'])->name('messages.store');
    Route::put('/messages/item/{message}', [MessageController::class, 'update'])->name('messages.update');
    Route::delete('/messages/item/{message}', [MessageController::class, 'destroy'])->name('messages.destroy');
    Route::patch('/messages/conversation/{student}/archive', [MessageController::class, 'archive'])->name('messages.archive');
    Route::delete('/messages/conversation/{student}', [MessageController::class, 'deleteConversation'])->name('messages.conversation.destroy');
    Route::get('/messages/{student}/updates', [MessageController::class, 'updates'])->middleware('throttle:60,1')->name('messages.updates');
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/requests', [ExcuseRequestController::class, 'index'])->name('requests.index');
    Route::put('/requests/settings', [ExcuseRequestSettingController::class, 'update'])->middleware('role:admin,program_head')->name('requests.settings.update');
    Route::middleware('role:student')->group(function () {
        Route::get('/requests/create', [ExcuseRequestController::class, 'create'])->name('requests.create');
        Route::post('/requests', [ExcuseRequestController::class, 'store'])->name('requests.store');
        Route::post('/requests/{excuseRequest}/submit', [ExcuseRequestController::class, 'submit'])->name('requests.submit');
        Route::patch('/requests/{excuseRequest}/attachment', [ExcuseRequestController::class, 'updateAttachment'])->name('requests.attachment.update');
    });
    Route::get('/request-documents/{document}', [ExcuseRequestController::class, 'document'])->name('requests.documents.show');
    Route::get('/requests/{excuseRequest}', [ExcuseRequestController::class, 'show'])->name('requests.show');
    Route::get('/requests/{excuseRequest}/slip', [ExcuseRequestController::class, 'slip'])->name('requests.slip');
    Route::post('/requests/{excuseRequest}/review', [WorkflowController::class, 'review'])->middleware('role:admin,program_head')->name('requests.review');
    Route::post('/requests/{excuseRequest}/acknowledge', [WorkflowController::class, 'acknowledge'])->middleware('role:faculty')->name('requests.acknowledge');
    Route::post('/requests/{excuseRequest}/complete', [WorkflowController::class, 'complete'])->middleware('role:faculty')->name('requests.complete');
    Route::get('/profile', [ProfileController::class, 'show'])->name('profile');
    Route::put('/profile', [ProfileController::class, 'updateDetails'])->name('profile.update');
    Route::put('/profile/password', [ProfileController::class, 'updatePassword'])->name('profile.password.update');
    Route::middleware('role:admin,program_head')->prefix('admin')->name('admin.')->group(function () {
        Route::get('/', fn () => redirect()->route('admin.students.index'))->name('index');
        Route::get('/students', [AdminStudentController::class, 'index'])->name('students.index');
        Route::get('/accounts', [UserAccountController::class, 'index'])->name('accounts.index');
        Route::get('/accounts/create', [UserAccountController::class, 'create'])->name('accounts.create');
        Route::post('/accounts', [UserAccountController::class, 'store'])->name('accounts.store');
        Route::get('/accounts/{account}/edit', [UserAccountController::class, 'edit'])->name('accounts.edit');
        Route::put('/accounts/{account}', [UserAccountController::class, 'update'])->name('accounts.update');
        Route::delete('/accounts/{account}', [UserAccountController::class, 'destroy'])->name('accounts.destroy');
        Route::get('/students/create', [AdminStudentController::class, 'create'])->name('students.create');
        Route::post('/students', [AdminStudentController::class, 'store'])->name('students.store');
        Route::delete('/students/bulk', [AdminStudentController::class, 'bulkDestroy'])->name('students.bulk-destroy');
        Route::get('/students/{student}', [AdminStudentController::class, 'show'])->name('students.show');
        Route::get('/students/{student}/assessment-form', [AdminStudentController::class, 'assessmentForm'])->name('students.assessment-form');
        Route::patch('/students/{student}/status', [AdminStudentController::class, 'toggleStatus'])->name('students.status');
        Route::patch('/students/{student}/academic-placement', [AdminStudentController::class, 'updateAcademicPlacement'])->name('students.academic-placement.update');
        Route::patch('/students/{student}/verify', [AdminStudentController::class, 'verify'])->name('students.verify');
        Route::patch('/students/{student}/decline', [AdminStudentController::class, 'decline'])->name('students.decline');
        Route::delete('/students/{student}', [AdminStudentController::class, 'destroy'])->name('students.destroy');
        Route::get('/instructors/create', [InstructorController::class, 'create'])->name('instructors.create');
        Route::post('/instructors', [InstructorController::class, 'store'])->name('instructors.store');
        Route::get('/subjects', [SubjectController::class, 'index'])->name('subjects.index');
        Route::get('/subjects/create', [SubjectController::class, 'create'])->name('subjects.create');
        Route::post('/subjects', [SubjectController::class, 'store'])->name('subjects.store');
        Route::get('/subjects/{subject}/edit', [SubjectController::class, 'edit'])->name('subjects.edit');
        Route::put('/subjects/{subject}', [SubjectController::class, 'update'])->name('subjects.update');
        Route::get('/instructor-assignments', [InstructorAssignmentController::class, 'index'])->name('instructor-assignments.index');
        Route::post('/instructor-assignments', [InstructorAssignmentController::class, 'store'])->name('instructor-assignments.store');
        Route::patch('/instructor-assignments/group/{faculty}/{course}/toggle', [InstructorAssignmentController::class, 'toggleGroup'])->name('instructor-assignments.group-toggle');
        Route::put('/instructor-assignments/group/{faculty}/{course}', [InstructorAssignmentController::class, 'updateGroup'])->name('instructor-assignments.group-update');
        Route::delete('/instructor-assignments/group/{faculty}/{course}', [InstructorAssignmentController::class, 'destroyGroup'])->name('instructor-assignments.group-destroy');
        Route::patch('/instructor-assignments/{assignment}/toggle', [InstructorAssignmentController::class, 'toggle'])->name('instructor-assignments.toggle');
        Route::delete('/instructor-assignments/{assignment}', [InstructorAssignmentController::class, 'destroy'])->name('instructor-assignments.destroy');
    });
});
