<?php
namespace App\Http\Controllers;
use App\Http\Requests\StoreExcuseRequest;
use App\Models\{ExcuseRequest,Subject,ReasonCategory,AcademicYear,Semester,SupportingDocument,InstructorAssignment};
use App\Services\RequestWorkflowService;
use Endroid\QrCode\Builder\Builder;
use Endroid\QrCode\ErrorCorrectionLevel;
use Endroid\QrCode\Writer\SvgWriter;
use Illuminate\Http\Request;
class ExcuseRequestController extends Controller {
    private function permitted(ExcuseRequest $e): bool{$u=auth()->user();return $u->role==='admin'||$u->role==='program_head'||($u->role==='student'&&$e->student_id===$u->student->id)||($u->role==='faculty'&&$e->facilitator_id===$u->faculty->id);}
    public function index(Request $r){$q=ExcuseRequest::with(['student.user','subject','facilitator.user']);$u=auth()->user();if($u->role==='student')$q->where('student_id',$u->student->id);if($u->role==='faculty')$q->where('facilitator_id',$u->faculty->id);if($r->filled('status'))$q->where('status',$r->status);if($r->filled('search'))$q->where(fn($x)=>$x->where('reference_number','like','%'.$r->search.'%')->orWhereHas('student.user',fn($y)=>$y->where('name','like','%'.$r->search.'%')));$requests=$q->latest()->paginate(15)->withQueryString();return view('requests.index',compact('requests'));}
    public function create(){ $student=auth()->user()->student;$assignments=InstructorAssignment::with(['subject','faculty.user'])->where('course_id',$student->course_id)->where('year_level',$student->year_level)->where('is_active',true)->get();return view('requests.form',['requestItem'=>new ExcuseRequest,'assignments'=>$assignments,'reasons'=>ReasonCategory::where('is_active',true)->get()]);}
    public function store(StoreExcuseRequest $r,RequestWorkflowService $flow){$data=$r->validated();unset($data['document'],$data['declaration'],$data['intent']);$student=$r->user()->student;$assignment=InstructorAssignment::where('course_id',$student->course_id)->where('year_level',$student->year_level)->where('subject_id',$data['subject_id'])->where('is_active',true)->first();if(!$assignment)return back()->withErrors(['subject_id'=>'This subject has no active instructor assignment for your course and year level.'])->withInput();$data+=['student_id'=>$student->id,'facilitator_id'=>$assignment->faculty_id,'academic_year_id'=>AcademicYear::where('is_current',true)->value('id'),'semester_id'=>Semester::where('is_current',true)->value('id'),'status'=>'draft'];$item=ExcuseRequest::create($data);$item->histories()->create(['new_status'=>'draft','action_by'=>$r->user()->id,'remarks'=>'Request created']);if($r->hasFile('document')){$f=$r->file('document');$item->documents()->create(['path'=>$f->store('supporting-documents'),'original_name'=>$f->getClientOriginalName(),'mime_type'=>$f->getMimeType(),'size'=>$f->getSize()]);}if($r->intent==='submit')$flow->transition($item,'submitted');return redirect()->route('requests.show',$item)->with('success','Your request has been saved.');}
    public function show(ExcuseRequest $excuseRequest){abort_unless($this->permitted($excuseRequest),403);$excuseRequest->load(['student.user','student.course','student.section','subject','facilitator.user','reasonCategory','histories.actor','documents']);return view('requests.show',['item'=>$excuseRequest]);}
    public function submit(ExcuseRequest $excuseRequest,RequestWorkflowService $flow){abort_unless(auth()->user()->role==='student'&&$excuseRequest->student_id===auth()->user()->student->id,403);$flow->transition($excuseRequest,'submitted');return back()->with('success','Request submitted for review.');}
    public function slip(ExcuseRequest $excuseRequest){abort_unless($this->permitted($excuseRequest)&&in_array($excuseRequest->status,['approved','acknowledged','completed']),403);$verificationUrl=route('verify',$excuseRequest->reference_number);$qrCode=(new Builder(writer:new SvgWriter(),data:$verificationUrl,errorCorrectionLevel:ErrorCorrectionLevel::Medium,size:220,margin:8))->build()->getDataUri();return view('requests.slip',['item'=>$excuseRequest->load(['student.user','student.course','student.section','subject','facilitator.user','reasonCategory']),'verificationUrl'=>$verificationUrl,'qrCode'=>$qrCode]);}
}
